language: python
# make it explicit that we favor the new container-based travis workers
sudo: false
python:
  # - "2.6"
  - "2.7"
  # - "3.5"
install: pip install -r requirements.txt
script: 
    - make test
    - make coverage
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/312b4616c796a425685a
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
before_install:
  - pip install codecov
after_success:
  - codecov
