id: {{gen_salt(8)}}
name: {{project}}
app:
  host: 127.0.0.1
  port: 3000
  debug: false
databases:
  mongo:
    dialect: mongodb
    host: 127.0.0.1
    port: 27017
    username: root
    password: ""
    database: test
  mysql:
    dialect: mysql
    host: 127.0.0.1
    port: 3306
    username: root
    password: ""
    database: test
cache:
  cache_type: redis
  cache_redis_url: redis://127.0.0.1:6379/2
celery:
  worker: 4
switch:
  cron:
    report_daily: False
